FROM ubuntu

MAINTAINER amazhara

RUN apt-get update && apt-get upgrade -y && apt-get install -y php7.2 php7.2-cli php7.2-common php7.2-json php7.2-opcache php7.2-mysql php7.2-zip php7.2-fpm php7.2-mbstring vim

# docker build -t ex03 . && docker run --rm -ti ex03
